---
- name: Role play only by root
  fail: msg="This role run only one time. ansible_user should not be 'ansible'"
  when: ansible_user == "ansible"

- name: Fail if system is not RHEL 7
  fail: msg="System is not RedHat family 7 distro"
  when: ansible_os_family != "RedHat" and ansible_distribution_major_version != "7"

- name: Fail if setup on BIOS software raid
  fail: msg="#### System installed on BIOS software RAID. /dev/{{ item.key }} Please disable Software RAID in bios and resetup server. Or disable this check by set in host vars --- 'ds_init_bios_soft_raid_warning:False'"
  when:
    - ds_init_bios_soft_raid_warning
    - item.key | search('md12')
  with_dict: "{{ ansible_devices }}"

- name: Abort if server type is not ds
  fail: msg="server type is not ds or vds"
  when: server_type != 'ds' and server_type != 'vds'

- import_tasks: sudoers.yml

- import_tasks: main_task.yml
  when: ansible_user == "root"

...
