---
# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: "mount: Remove swapfile from /etc/fstab"
  mount:
    name: swap
    fstype: swap
    state: absent

- name: "command: Disable swap"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
...
