- name: create southbridge directories
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /srv/southbridge/bin
    - /srv/southbridge/etc
    - /srv/southbridge/check
    - /srv/southbridge/scripts
    - /var/lib/flags
    - /etc/monit.d/template

- name: copy monit configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'vs/etc/monit.d/template/system',
        dest: '/etc/monit.d/template/system',
        mode: '0444' }
  when:
    - virtualization_type != 'docker'
  notify: restart monit

- name: copy configs vs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'vs/etc/sysconfig/named',
        dest: '/etc/sysconfig/named',
        mode: '0444' }
  when: server_type == 'vs'

- name: template configs vs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'vs/etc/sysctl.conf.j2',
        dest: '/etc/sysctl.conf',
        mode: '0444' }
    - { src: 'vs/etc/security/limits.d/90-nproc.conf',
        dest: '/etc/security/limits.d/90-nproc.conf',
        mode: '0444' }
  when: server_type == 'vs'
  tags: [ sysctl ]
