---
- name: "{{ base_iptables_service }} service script"
  template:
    src: "iptables/{{ base_iptables_script }}.j2"
    dest: "{{ base_sb_libexec }}/{{ base_iptables_script }}"
    mode: 0744
  register: base_iptables_script_result
  tags: [ iptables ]

- name: "{{ base_iptables_service }} service unit"
  template:
    src: "iptables/{{ base_iptables_service }}.service.j2"
    dest: "/etc/systemd/system/{{ base_iptables_service }}.service"
    mode: 0644
  register: base_iptables_unit_result
  tags: [ iptables ]

- name: "{{ base_iptables_service }} service {{ base_iptables_enable|ternary('enabled','disabled') }} (systemd)"
  systemd:
    name: "{{ base_iptables_service }}"
    state: "{{ base_iptables_enable|ternary('started','stopped') }}"
    enabled: "{{ base_iptables_enable|ternary('yes','no') }}"
  tags: [ iptables ]

- name: "{{ base_iptables_service }} service reloaded (systemd)"
  systemd:
    name: "{{ base_iptables_service }}"
    state: reloaded
  when: base_whitelist.changed
  tags: [ iptables ]

- name: "{{ base_iptables_service }} service restarted (systemd)"
  systemd:
    name: "{{ base_iptables_service }}"
    state: restarted
    daemon_reload: yes
  when: base_iptables_unit_result.changed or base_iptables_script_result.changed
  tags: [ iptables ]
...
