---
- name: Base iptables configuration file
  template:
    src: "iptables/iptables.j2"
    dest: "/etc/sysconfig/iptables"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: [ iptables ]

- name: Check required dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ base_sb_check }}"
    - "{{ base_sb_libexec }}"
    - "{{ base_sb_etc }}"
  tags: [ iptables ]

- name: Iptables whitelist
  template:
    src: "iptables/{{ base_iptables_config }}.j2"
    dest: "{{ base_sb_etc }}/{{ base_iptables_config }}"
    mode: 0644
  register: base_whitelist
  tags: [ iptables ]

- include: "iptables-sysvinit.yml"
  when: ansible_distribution_major_version|int <= 6

- include: "iptables-systemd.yml"
  when: ansible_distribution_major_version|int >= 7

- name: Iptables service check script
  template:
    src: "iptables/{{ base_iptables_check_script }}.j2"
    dest: "{{ base_sb_check }}/{{ base_iptables_check_script }}"
    mode: 0755
  tags: [ iptables ]
...
