- name: copy /etc/resolv.conf
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etc/resolv.conf.j2',
        dest: '/etc/resolv.conf',
        mode: '0644' }
  when: (server_type == 'ds') or (base_resolv_conf is defined) or ((server_type != 'ds') and base_named_enable)
  tags: [ resolvconf ]

- name: install named
  become: true
  yum:
    name: bind
    state: present

- name: "service named {{ base_named_enable|ternary('started','stopped')}}"
  become: true
  service:
    name: named
    state: "{{ base_named_enable|ternary('started','stopped')}}"
    enabled: "{{ base_named_enable|ternary('yes','no')}}"
  when:
    - ( server_type == 'vs' ) or ( server_type == 'vds' )
